---
name: CI/CD
'on':
  pull_request:
  push:

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt-hotspot'

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          gradle-version: 5.6.4

      - name: Build and verify
        run: gradle build
