---
name: Release
on:
  push:
    branches:
      - "feature/publish-to-maven-central"

jobs:
  build:
    name: Release new version
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: read
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt-hotspot'

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          gradle-version: 5.6.4

      - name: Application Version
        id: build_number
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          search_commit_body: true
          debug: true

      - name: Assemble zip distribution
        run: "gradle distZip -Pversion=1.0.0"

      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "gradle publish -Pversion=1.0.0"

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1.0.0"
          prerelease: false
          title: "v1.0.0"
          files: |
            build/distributions/*.zip
