---
name: CI/CD
# 'on':
#   pull_request:
#   push:

on:
  push:
    branches:
      - "feature/ci"

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: read
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt-hotspot'

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          gradle-version: 5.6.4

      - name: Build and verify
        run: gradle build

      - name: Application Version
        id: build_number
        uses: paulhatch/semantic-version@v5.3.0
        with:
            tag_prefix: "v"

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.build_number.outputs.major }}.${{ steps.build_number.outputs.minor }}.${{ steps.build_number.outputs.increment }}
          prerelease: false
          title: "Development Build"
          files: |
            build/distributions/*.jar
